import {
  brands,
  displaySizeOptions,
  // processorOptions,
  ramOptions,
  storageOptions,
} from "../constants";
import { Product } from "../../models/product";

export const generateMockProducts: Product[] = [
  ...Array.from({ length: 100 }, (_, i) => {
    const id = i + 1;
    const models = [
      "ProBook",
      "VivoBook",
      "ThinkPad",
      "Swift",
      "Inspiron",
      "MacBook",
      "GalaxyBook",
      "Satellite",
      "Surface",
      "Modern",
    ];
    const brand = brands[Math.floor(Math.random() * brands.length)];
    const model = models[Math.floor(Math.random() * models.length)];
    const randomNum = Math.floor(Math.random() * 9000) + 1000;
    const name = `${brand} ${model} ${randomNum}`;
    const category = "Laptop";
    const basePrice = Math.floor(Math.random() * 15000000) + 3500000;
    const price = `Rp. ${basePrice.toLocaleString("id-ID")}`;
    const ram = ramOptions[Math.floor(Math.random() * ramOptions.length)];
    const storage =
      storageOptions[Math.floor(Math.random() * storageOptions.length)];
    const processor: "Intel" | "AMD" | "Apple" =
      brand == "Apple"
        ? "Apple"
        : (["Intel", "AMD"][Math.floor(Math.random() * 2)] as "Intel" | "AMD");
    const displaySize =
      displaySizeOptions[Math.floor(Math.random() * displaySizeOptions.length)];
    const hasDiscount = Math.random() > 0.7;
    const discount = hasDiscount
      ? Math.floor(Math.random() * 30) + 5
      : undefined;
    const priceAfterDiscount = hasDiscount
      ? `Rp. ${(
          basePrice - Math.floor(basePrice * (discount! / 100))
        ).toLocaleString("id-ID")}`
      : undefined;
    const badge = hasDiscount ? `Diskon ${discount}%` : "";
    return {
      id,
      name,
      category,
      brand,
      price,
      img: "/temp/laptop.jpg",
      badge,
      discount,
      priceAfterDiscount,
      ram,
      storage,
      processor,
      displaySize,
    };
  }),
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Lenovo GalaxyBook 4667",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 8.858.246",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "256GB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 2,
    name: "Dell ProBook 6256",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 16.881.579",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "512GB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 3,
    name: "Apple Inspiron 2181",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 8.990.401",
    img: "/temp/laptop.jpg",
    badge: "Diskon 27%",
    discount: 27,
    priceAfterDiscount: "Rp. 6.562.993",
    ram: 32,
    storage: "256GB",
    processor: "Apple",
    displaySize: 14,
  },
  {
    id: 4,
    name: "Apple ProBook 7094",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 14.176.933",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "Apple",
    displaySize: 14,
  },
  {
    id: 5,
    name: "Apple Inspiron 1016",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 7.280.531",
    img: "/temp/laptop.jpg",
    badge: "Diskon 32%",
    discount: 32,
    priceAfterDiscount: "Rp. 4.950.762",
    ram: 8,
    storage: "512GB",
    processor: "Apple",
    displaySize: 14,
  },
  {
    id: 6,
    name: "Lenovo GalaxyBook 7167",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 6.920.605",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "512GB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 7,
    name: "HP Modern 3009",
    category: "Laptop",
    brand: "HP",
    price: "Rp. 15.051.398",
    img: "/temp/laptop.jpg",
    badge: "Diskon 17%",
    discount: 17,
    priceAfterDiscount: "Rp. 12.492.661",
    ram: 4,
    storage: "1TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 8,
    name: "HP GalaxyBook 7544",
    category: "Laptop",
    brand: "HP",
    price: "Rp. 18.390.163",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "256GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 9,
    name: "Acer VivoBook 4920",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 8.114.772",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 10,
    name: "Toshiba GalaxyBook 9097",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 17.727.271",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 11,
    name: "Asus VivoBook 4354",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 7.232.367",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "1TB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 12,
    name: "Toshiba ThinkPad 6050",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 12.909.712",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "512GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 13,
    name: "MSI ProBook 7190",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 4.597.523",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "1TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 14,
    name: "MSI Satellite 1226",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 13.905.460",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 15,
    name: "Lenovo Inspiron 1268",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 8.978.160",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "512GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 16,
    name: "Acer GalaxyBook 1252",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 8.016.056",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 17,
    name: "Lenovo ThinkPad 5106",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 16.445.311",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "2TB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 18,
    name: "Dell Surface 3260",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 7.813.637",
    img: "/temp/laptop.jpg",
    badge: "Diskon 29%",
    discount: 29,
    priceAfterDiscount: "Rp. 5.547.683",
    ram: 8,
    storage: "512GB",
    processor: "Intel",
    displaySize: 16,
  },
  {
    id: 19,
    name: "Samsung Swift 5811",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 18.408.018",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "2TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 20,
    name: "Dell VivoBook 7445",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 14.330.180",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "1TB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 21,
    name: "Acer Swift 8630",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 11.027.000",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "2TB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 22,
    name: "Samsung Swift 3121",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 12.810.996",
    img: "/temp/laptop.jpg",
    badge: "Diskon 9%",
    discount: 9,
    priceAfterDiscount: "Rp. 11.658.007",
    ram: 4,
    storage: "2TB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 23,
    name: "Dell MacBook 1302",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 7.625.289",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "1TB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 24,
    name: "MSI Modern 6246",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 15.341.662",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "256GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 25,
    name: "Toshiba ProBook 5551",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 5.469.445",
    img: "/temp/laptop.jpg",
    badge: "Diskon 17%",
    discount: 17,
    priceAfterDiscount: "Rp. 4.539.640",
    ram: 32,
    storage: "256GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 26,
    name: "Acer ProBook 9304",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 5.049.864",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "256GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 27,
    name: "Apple Satellite 2411",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 4.009.479",
    img: "/temp/laptop.jpg",
    badge: "Diskon 20%",
    discount: 20,
    priceAfterDiscount: "Rp. 3.207.584",
    ram: 32,
    storage: "1TB",
    processor: "Apple",
    displaySize: 14,
  },
  {
    id: 28,
    name: "Samsung Inspiron 3272",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 13.373.850",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 29,
    name: "MSI Satellite 7984",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 11.868.923",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "512GB",
    processor: "Intel",
    displaySize: 16,
  },
  {
    id: 30,
    name: "Acer Swift 8082",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 13.782.618",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 31,
    name: "Samsung Surface 4752",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 16.111.863",
    img: "/temp/laptop.jpg",
    badge: "Diskon 20%",
    discount: 20,
    priceAfterDiscount: "Rp. 12.889.491",
    ram: 32,
    storage: "1TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 32,
    name: "Lenovo ProBook 7608",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 3.850.304",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "1TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 33,
    name: "Asus ThinkPad 5507",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 7.133.508",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "2TB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 34,
    name: "Samsung MacBook 6793",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 17.883.520",
    img: "/temp/laptop.jpg",
    badge: "Diskon 8%",
    discount: 8,
    priceAfterDiscount: "Rp. 16.452.839",
    ram: 16,
    storage: "2TB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 35,
    name: "Apple Satellite 2596",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 6.810.805",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "2TB",
    processor: "Apple",
    displaySize: 13,
  },
  {
    id: 36,
    name: "Microsoft Satellite 6184",
    category: "Laptop",
    brand: "Microsoft",
    price: "Rp. 3.506.364",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "256GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 37,
    name: "Acer MacBook 4594",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 6.644.308",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "1TB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 38,
    name: "Dell Inspiron 8661",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 8.795.728",
    img: "/temp/laptop.jpg",
    badge: "Diskon 6%",
    discount: 6,
    priceAfterDiscount: "Rp. 8.267.985",
    ram: 32,
    storage: "2TB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 39,
    name: "Lenovo Satellite 1815",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 13.476.778",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "256GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 40,
    name: "Apple MacBook 8043",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 11.400.183",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "512GB",
    processor: "Apple",
    displaySize: 16,
  },
  {
    id: 41,
    name: "MSI ThinkPad 7010",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 4.448.765",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "256GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 42,
    name: "Microsoft Inspiron 6287",
    category: "Laptop",
    brand: "Microsoft",
    price: "Rp. 13.273.151",
    img: "/temp/laptop.jpg",
    badge: "Diskon 17%",
    discount: 17,
    priceAfterDiscount: "Rp. 11.016.716",
    ram: 32,
    storage: "1TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 43,
    name: "Apple Surface 1475",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 11.435.312",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "256GB",
    processor: "Apple",
    displaySize: 16,
  },
  {
    id: 44,
    name: "Apple Satellite 9191",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 14.844.501",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "1TB",
    processor: "Apple",
    displaySize: 16,
  },
  {
    id: 45,
    name: "Apple MacBook 6739",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 16.027.643",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "2TB",
    processor: "Apple",
    displaySize: 13,
  },
  {
    id: 46,
    name: "Samsung Surface 5769",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 15.045.589",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 47,
    name: "Dell Inspiron 8724",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 5.415.979",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 48,
    name: "Lenovo Inspiron 2821",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 11.609.250",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "512GB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 49,
    name: "Dell Inspiron 8956",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 7.203.234",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "1TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 50,
    name: "Microsoft Surface 5363",
    category: "Laptop",
    brand: "Microsoft",
    price: "Rp. 17.528.776",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "512GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 51,
    name: "Dell VivoBook 8239",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 5.689.492",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 52,
    name: "MSI ProBook 5427",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 7.034.145",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "1TB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 53,
    name: "Asus ThinkPad 1715",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 10.282.484",
    img: "/temp/laptop.jpg",
    badge: "Diskon 19%",
    discount: 19,
    priceAfterDiscount: "Rp. 8.328.813",
    ram: 32,
    storage: "256GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 54,
    name: "Lenovo VivoBook 5821",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 11.361.855",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "256GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 55,
    name: "MSI Satellite 8928",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 17.442.397",
    img: "/temp/laptop.jpg",
    badge: "Diskon 13%",
    discount: 13,
    priceAfterDiscount: "Rp. 15.174.886",
    ram: 32,
    storage: "256GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 56,
    name: "Apple Surface 2723",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 10.898.256",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "512GB",
    processor: "Apple",
    displaySize: 13,
  },
  {
    id: 57,
    name: "Toshiba Satellite 9268",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 16.931.653",
    img: "/temp/laptop.jpg",
    badge: "Diskon 9%",
    discount: 9,
    priceAfterDiscount: "Rp. 15.407.805",
    ram: 16,
    storage: "1TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 58,
    name: "MSI GalaxyBook 9984",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 17.393.661",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "1TB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 59,
    name: "Asus ProBook 5748",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 12.875.454",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "512GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 60,
    name: "Toshiba MacBook 1760",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 11.755.653",
    img: "/temp/laptop.jpg",
    badge: "Diskon 25%",
    discount: 25,
    priceAfterDiscount: "Rp. 8.816.740",
    ram: 8,
    storage: "2TB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 61,
    name: "Lenovo MacBook 7082",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 6.327.087",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "256GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 62,
    name: "MSI Inspiron 5807",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 4.086.457",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "256GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 63,
    name: "Samsung ThinkPad 7341",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 8.442.534",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "256GB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 64,
    name: "Toshiba Satellite 9693",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 17.182.148",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 65,
    name: "Acer MacBook 5307",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 18.001.860",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "1TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 66,
    name: "Microsoft GalaxyBook 8878",
    category: "Laptop",
    brand: "Microsoft",
    price: "Rp. 6.380.333",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "2TB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 67,
    name: "Toshiba Surface 1585",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 17.535.517",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "512GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 68,
    name: "Toshiba Inspiron 6224",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 8.846.663",
    img: "/temp/laptop.jpg",
    badge: "Diskon 13%",
    discount: 13,
    priceAfterDiscount: "Rp. 7.696.597",
    ram: 16,
    storage: "512GB",
    processor: "Intel",
    displaySize: 16,
  },
  {
    id: 69,
    name: "Acer ProBook 4442",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 15.421.426",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "256GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 70,
    name: "MSI Satellite 4773",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 14.363.247",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "256GB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 71,
    name: "Lenovo GalaxyBook 6108",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 14.195.103",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "256GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 72,
    name: "Dell Surface 7485",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 14.218.123",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "512GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 73,
    name: "Microsoft Satellite 7736",
    category: "Laptop",
    brand: "Microsoft",
    price: "Rp. 16.797.962",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "2TB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 74,
    name: "Toshiba Inspiron 1723",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 14.660.764",
    img: "/temp/laptop.jpg",
    badge: "Diskon 24%",
    discount: 24,
    priceAfterDiscount: "Rp. 11.142.181",
    ram: 32,
    storage: "512GB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 75,
    name: "MSI Modern 2848",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 8.891.434",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 76,
    name: "Dell Swift 9499",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 8.601.368",
    img: "/temp/laptop.jpg",
    badge: "Diskon 28%",
    discount: 28,
    priceAfterDiscount: "Rp. 6.192.985",
    ram: 16,
    storage: "2TB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 77,
    name: "Dell Satellite 7832",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 13.671.402",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "512GB",
    processor: "AMD",
    displaySize: 13,
  },
  {
    id: 78,
    name: "Acer GalaxyBook 3160",
    category: "Laptop",
    brand: "Acer",
    price: "Rp. 9.353.259",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "256GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 79,
    name: "Toshiba Inspiron 9693",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 12.323.350",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 80,
    name: "Lenovo GalaxyBook 1319",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 12.280.622",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "2TB",
    processor: "Intel",
    displaySize: 16,
  },
  {
    id: 81,
    name: "Microsoft Surface 3731",
    category: "Laptop",
    brand: "Microsoft",
    price: "Rp. 5.492.376",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "256GB",
    processor: "Intel",
    displaySize: 16,
  },
  {
    id: 82,
    name: "HP Surface 1801",
    category: "Laptop",
    brand: "HP",
    price: "Rp. 9.242.437",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 83,
    name: "Asus ThinkPad 6691",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 17.518.006",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "1TB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 84,
    name: "Dell ThinkPad 2651",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 7.254.742",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "512GB",
    processor: "AMD",
    displaySize: 15,
  },
  {
    id: 85,
    name: "Lenovo VivoBook 2615",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 4.476.959",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "2TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 86,
    name: "Lenovo Swift 5118",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 17.185.161",
    img: "/temp/laptop.jpg",
    badge: "Diskon 16%",
    discount: 16,
    priceAfterDiscount: "Rp. 14.435.536",
    ram: 24,
    storage: "512GB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 87,
    name: "Toshiba Swift 5764",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 12.550.004",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 88,
    name: "Toshiba Modern 7066",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 15.665.007",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "1TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 89,
    name: "Asus Inspiron 2889",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 14.558.881",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "512GB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 90,
    name: "MSI Satellite 7001",
    category: "Laptop",
    brand: "MSI",
    price: "Rp. 9.062.565",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "256GB",
    processor: "AMD",
    displaySize: 16,
  },
  {
    id: 91,
    name: "Toshiba Inspiron 2313",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 6.626.238",
    img: "/temp/laptop.jpg",
    badge: "Diskon 29%",
    discount: 29,
    priceAfterDiscount: "Rp. 4.704.629",
    ram: 32,
    storage: "1TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 92,
    name: "Apple MacBook 9639",
    category: "Laptop",
    brand: "Apple",
    price: "Rp. 15.446.569",
    img: "/temp/laptop.jpg",
    badge: "Diskon 32%",
    discount: 32,
    priceAfterDiscount: "Rp. 10.503.667",
    ram: 4,
    storage: "256GB",
    processor: "Apple",
    displaySize: 16,
  },
  {
    id: 93,
    name: "HP Surface 9181",
    category: "Laptop",
    brand: "HP",
    price: "Rp. 4.538.970",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 4,
    storage: "256GB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 94,
    name: "Asus ThinkPad 3860",
    category: "Laptop",
    brand: "Asus",
    price: "Rp. 16.871.781",
    img: "/temp/laptop.jpg",
    badge: "Diskon 19%",
    discount: 19,
    priceAfterDiscount: "Rp. 13.666.143",
    ram: 16,
    storage: "512GB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 95,
    name: "HP VivoBook 8593",
    category: "Laptop",
    brand: "HP",
    price: "Rp. 12.608.490",
    img: "/temp/laptop.jpg",
    badge: "Diskon 28%",
    discount: 28,
    priceAfterDiscount: "Rp. 9.078.113",
    ram: 24,
    storage: "1TB",
    processor: "AMD",
    displaySize: 14,
  },
  {
    id: 96,
    name: "Samsung GalaxyBook 2274",
    category: "Laptop",
    brand: "Samsung",
    price: "Rp. 16.688.577",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 24,
    storage: "2TB",
    processor: "Intel",
    displaySize: 15,
  },
  {
    id: 97,
    name: "Dell MacBook 9837",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 14.399.231",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 16,
    storage: "1TB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 98,
    name: "Lenovo Surface 3103",
    category: "Laptop",
    brand: "Lenovo",
    price: "Rp. 13.116.907",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 32,
    storage: "256GB",
    processor: "Intel",
    displaySize: 13,
  },
  {
    id: 99,
    name: "Toshiba ProBook 6931",
    category: "Laptop",
    brand: "Toshiba",
    price: "Rp. 9.910.563",
    img: "/temp/laptop.jpg",
    badge: "",
    ram: 8,
    storage: "1TB",
    processor: "Intel",
    displaySize: 14,
  },
  {
    id: 100,
    name: "Dell VivoBook 7256",
    category: "Laptop",
    brand: "Dell",
    price: "Rp. 15.215.131",
    img: "/temp/laptop.jpg",
    badge: "Diskon 16%",
    discount: 16,
    priceAfterDiscount: "Rp. 12.780.711",
    ram: 4,
    storage: "2TB",
    processor: "AMD",
    displaySize: 13,
  },
];
